### ISSUE TITLE
the time is very short background 

### ISSUE THREAD

**Issue by srsarcasmo** [jocull/phonegap-backgroundjs#7]
in ios 4 does not work, the time is very short background or tell me how to configure the plugin .. are thanked

**Comment by jocull** [comment]
Sorry, I have not used this in a long time and I don't know how well it is
working at this point in time.

Also where are you using an iOS 4 device? I have not seen one of those in a
long long time. Even an iPhone 3GS can use iOS 6.

**Comment by srsarcasmo** [comment]
window.plugins.backgroundjs.lockBackgroundTime();
                          window.plugins.backgroundjs.lockBackgroundTime(60000);
                          window.plugins.backgroundjs.setBackgroundSeconds(600000);



Is this the correct way to use the plugin?

**Comment by jocull** [comment]
That looks correct to me. You can see the sources here:

https://github.com/jocull/phonegap-backgroundjs/blob/master/src/js/BackgroundJS.js

You should probably be using callbacks to see if any success or error messages come through.

**Comment by srsarcasmo** [comment]
Friend, perhaps I should specify the package of my application and also the javascript function that I will use in the following sections?

<feature name="BackgroundJS">
        <param name="ios-package" value="BackgroundJS"/>

**Comment by srsarcasmo** [comment]
`<feature name="BackgroundJS">
        <param name="ios-package" value="BackgroundJS"/>`

**Comment by jocull** [comment]
This all looks correct to me, but unfortunately I am not really able to help much. You could try setting breakpoints in the iOS code and see if the step debugger will hit them.

**Comment by srsarcasmo** [comment]
Because in your project is set 60 and my only let me be 6 minutes in the background, tell me how to do it to delay more time in the background, maybe the browser that loses focus or maybe the operating system is killing my setinterval, or maybe the Plugin if it works but needs to set more time

**Comment by jocull** [comment]
I don't know that 6 minutes is allowed in the background. iOS has pretty strict limits about when background is allowed, for example audio must be playing or a network operation must be in progress. You should consider looking at the docs for that.

**Comment by srsarcasmo** [comment]
Friend, your plugin works, but maybe the service only lasts a few minutes depending on the cpu and the system; So I would like if you can give me some idea how I can manipulate the BackgroundJS.m file to last longer or have to goqe to see the declaration in window.plugins.backgroundjs.lockBackgroundTime (600); ? I am only writing this line with a value at 600, that leaves me only about 6 minutes, if I modify it to 800 or 1200 my application lasts less hard only about 3 minutes, I need help with this or explain where I need to modify

**Comment by jocull** [comment]
Sorry, I am not familiar with the specifics of how this works exactly as it varies by application and scenario. Please see the [Apple documentation here](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html) for more information and I would encourage you to ask any [iOS specific questions on StackOverflow](http://stackoverflow.com/questions/tagged/ios). Hope that helps! Good luck!
