### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by t2wu** [jocull/phonegap-backgroundjs#8]
The plugin used to work. Now I can't even add it to a project.

What does people usually do when they need async work in the background but need to tell the OS so it doesn't put the app to sleep?

**Comment by jocull** [comment]
I'm not aware of any alternatives, but to be honest I haven't ever looked for them. I don't get a chance to do much mobile development these days.

Assuming Cordova native plugins still are a thing (I don't know how they would not be), the code that powers this plugin for [iOS is actually very small](https://github.com/jocull/phonegap-backgroundjs/blob/898b0be3a504b9eb14bf5fc34b48ebaeef7723e7/Objective-C/BackgroundJS.m).

I would be surprised if the same strategy isn't valid on iOS for legacy reasons. With probably pretty minimal work the project could be updated to the latest Cordova standards. Hope that helps!

**Comment by jocull** [comment]
These docs probably help:

https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html#publishing-plugins

I also found some references that say you may be able to use the old plugin registry, but I don't know that I ever published it there. Perhaps a reference to the Github URL is all you need? That is a long shot, but I've used it to work around things not being published to npm before.

https://cordova.apache.org/plugins/faq.html

**Comment by t2wu** [comment]
I added package.json and make version string A.B.C format to be compatible to newer version of Cordova. It is now able to be added to the Cordova project.

[https://github.com/t2wu/phonegap-backgroundjs/tree/t2wu](url)

**Comment by jocull** [comment]
Nice work! I merged this just now in #9 to help future users. Thank you!
